---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: searxng-secrets
  namespace: searxng
spec:
  encryptedData:
    SEARXNG_SECRET: AgCKPNe5HVOenagIS+ibudJfjRsKlro45vnlnco7qDgawSp21t/mJWFhdR17B2BevvyLJkly8hHBB0oNzOCc4cwfYfNL18Y0g2jqBz81QULLJ+Z6wxwFVFAcNE27rwAZpwTY1ZjXxAID1sTZfdBHR12Bl3vdEVGN9y3KNdu8/UO0hAAUNr4X7andjQazFMkvApv+gFJRAGp/ngc3AAGCijtTT9PfZTWRUK9gJ/AqsGjwrlwXOktSDYlGkdARLbkQJ6sAKipds5YbdaH/V2I6g6sf5gox0AVVHXrcJAyyEhRcoWI0baE+T5hjm9tU+++hbLxAdPmhDqjz63YdthzJHU7RELAaOK9qlsS7SZMv6ywNBxDDTMIOQ1tQ+ZIItbmLMBd8jQtI4aMmEz2RBdhM15vb/8HRqSD8B7KoR0bDhORSb97lWZjJNNwU/EqEujHgUEcqCsHJ5h/JKGohFIVSk3WpdHJvzS4iAQwju0q0tNzsMzX9MonKSLHDWEA8YUfMAH62yTErbh4tOSqPkvFNPR58HfVpNW+OvHhYG6vJ7f27OhOZblEWZRsiYXHL0B1HHX1fx3MtTABsvxqPFadLA5RbVe8ZSISmgnPb3rGUEy1ZK8+dBX53uUHD0K7NZ5g+CwTlMQFAzo5esV8MzmvcDpUpPhvzeNm4d9Z8yFwQ4zNCspsCcU6AdzoIq7dO5iLACdk52Buy+kg7urNM2kf+oExPjwrf2fWbeUC26e4byiRIAA==
  template:
    metadata:
      creationTimestamp: null
      name: searxng-secrets
      namespace: searxng
    type: Opaque
