---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudnative-pg-cluster-os2adgang
  namespace: os2adgang
spec:
  encryptedData:
    password: AgCquQlLIacsYjUJFSq3yD6Lhm7q348jnsU1oqmY4P+vqmgsmgEWDI5kkG/11eRAQh1lPLJ/nRWpEnuez2rzd5MVSBgDZx4FrHa1g5WlNadsAlByN8B8PNQd6gBLJCx3zMetffRjgEhYsmzlLL4ukoRuEAwdlGyo5FTM9sP1rVVyV42eLckHleKeWKV2msdziATTjUw3uEaVc90fh8ktH3XxL6dBHhS9K9KHOLaDrOe+Zvj+YvFVtiTHtdwQpAkmI4NS6yjk97S1ZVxZd5MfLdJMrGiuMIEqVVld3pviMw45QCye7pICs/SFZTwsG3e4JmoXP4o4WmbSD2sUWAKjH5RE4TbjUseDce5MJnlvb8DTZYqjFk1uEJeEYIYGdbrL+y9yHbFprEh1mrlTiQ6NAX+VhxyVRoVWprdCpdKfUak7JFea7CT0PLqQCZgjhOAFRx0aNkmucjKP2bEfDb1ahZeZSDa2IfHdCUeb8LLWe1CFFWbdjFhV+/3wwJKXr7iv8riYbGVNCYBZ2zkHPbn9wpFdbJeZ5Bn9FWljTvl1wDEVCenPqDueS6cmhmtAq3RNJo/1yyJ/MO3u6E3hKqoGx0obLxLQ/mpw1nm//nDb2UiOPSAqiDRF7mprxybCNeV2rL+iXRvT/QWFOx2EOhTsgrPdezv6aCwn6W/zYKcH8/c/tW010Qw9fHXoPPb7UHhM+dLq7yfoNCURi6cpd/J4dm8LCYN7F8fEdu3TBLD9wExUbezzz2R9pjH3kofFRq07CHIzqdKtHUkSVG4Iix+2oXKs
    username: AgAuP2Bxqgsb0yp4+ZS8eWDjLqeVmDb70xddvoRYMM2Vw0sO25QZQjpbVjjFLCxkdPDVEhWNAgUPJeh9IYeCKUGWkDq/KHjkzL4WhxfkLsGv1dVyQg7lKL32So8tArc3g/bc5LKTeqdg5fToI/922gpbYwSrUyCBtBrsANYzKrebxE41wSg0YzwXRC701Rq7Nutl8IDUUigT756ToARDitu6HRZy6FG83kIMuEoUvB+Ut3FmU2Mu5NA/u7A1wR1rdvzQZeWQ804O12kQmytmbTUNRaEdtkplOebX3uV692l3PtvUuzQxJbJCehtvQ4f2PbD84nxMGw7bX3UIx0hfmg27VP78MEj3Q20c7Y7jtRm/B5Stt0B/TuGjAmohsnZjv4vfdAy/YisL1BbmM4tK9XlWBNTZ6NZPFYYNgFuznuGx+Ez7g9XA8aDk/ofS9yG3vgFNUIQBbdVD+nMAb2NDpOx2W5sM8iDKAME3vVqofemdsklkh7Ki7M9YcrRh9ybzzT0LyokTuFKbilQh5eXhvSNcJ3wKlVW4RIkYgX+HhK8pYeVxfUUOVvfCvQxLVCDv/U7glxCjuXYmP01TOhVJXa0RsxhTKgZWpiGirJDDrm46rLlFOFENbtp4H9FdS2g5M2g3XvS9JkyJhk7FG4CeNiJldX7Bzu3AxAEvxSKaviA74Fbi2afSFWLwhTAAxXAsSQQXNJJYL+SvYpM=
  template:
    metadata:
      creationTimestamp: null
      name: cloudnative-pg-cluster-os2adgang
      namespace: os2adgang
    type: Opaque
