---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: litellm-secrets
  namespace: litellm
spec:
  encryptedData:
    CA_VLLM_LOCAL_API_KEY: AgAOIN+syfhW4kTJe1KYopXdSPjwp/jOY+d5YnXoVRzCgsa/wN4270aRkE2h8v4AhAplXg2FSd8dkRPuSx4GEWGQvvZ1IsCZ5OjirFfr9FSsvYNuQDyEL8ggNlY0LXg3zpHYD4oTsI1cxJI/9qa5UZWzFmKGyn3I4EkCB3ImpQgRUeeMO+wF3r7R76Tu4D4JajDOBWTUn/SnvN1PfWDSCH5WAKwfxoujwh3RXai3XtU6tuXziXkPpilNnvUFvqBhWrOyeaVwYuiOELwGJQV4yU5hzFr8b/m4LacldEvUgLlUHQvCG029jACZzUThdpXdAhGpwjJj5bxdyR3dpJu80VBaNUWUg6oXvo7K7SzUD4W81fLL7Wi7vAlNLyP303fo+RSlTD+nYLuzIuX9Fz+5DqjDtx1HNbWKRLVmfRJshtTwby4pTMeZbKoftTpk0uzB6XxLbWkJFMqT7LMyL69QfMC1v414v2aBcaNSOivunHodDr2Cyv/TdbnE+vG+wwjbgOdWx6VNKCrQDzcx6FIWSRraA1rDeU+4IyN7cPvElzHtzKDGzqyJVNf2YiHJKOYfGPgejevdx8PbugoY9MRd367FvBzRtUNWm0J1q+aXw5h/XA5zbM51eHfojlxaMJXAWBtDvDPeARZ/8Q5WkKRz+2j/WEdZA8RJdy/Clmo0pkFtGAvhJ7UQpU084xVoQEpWS2x9SEu2sX7IDQB1AtO0LXLvIS94pEh2oLtSruFzlwnu7A==
    PROXY_MASTER_KEY: AgBvmUqUz3MoMTmYwy7os1XbtI09aRxiTfhutwjEvm+CDxbLaYHXIoC0fF0HtDXOXa/aK5rYSnxRviCsjp7J3DAsM9ScUA7NQVCGc3rGuatys5xYYOHHUNCZU7LIs6WYDK28aV5szT3EQ+c8hrO5/Gsn1y/dqg23234i/lTJwm1/lh42duTl8lr5ojVRYvbVxbCTIWIj8HDj97LwtoTkPjEaVbrKf6mnmvzslYQf8O3ZpXPlQD5CJna5ajhl6qF7NC7TUNKlN3pqLCTK3EruZcdgLtP4Shruc8/zEpRJZjTtT4H2O7lRTUmOW+XaTaAe9jdTKY/UDUzrr67PAMWDXYnd7HHdt8KqVn0KT/ejUZ1iO4xwOm96Ng6kZ15gCOvE2nY9FJaH69cKV82LPfohSooHoGKRCZQiPKEmLOANzv/upcLsMb1EZbl+huoTMeOLCdIVinn8uIQOptIJzqDquCgdZTYWT6SdIgd0lrRPmJZK4pDt+J3klBYjn1Jpeu4tHyjCYnrLrNHgiT/so/GGVCIjNU6S5Uqi/7J/5+xESbg9N+AwPfLKQYbzS/eAbQjMJVuXzMT3VpDrdcLgeVljWLPh5VyKYB5TV2r7hwzG+aqDbytxJs/vjl54barp2PyToizN50QLBBZyCOabT5DHXYcNXQXj5fv/xSDfB8LQuZ0pT1rvcQqdKakP3ztRRlzfIy4LaZwL/AMcLgz1Q2wGrnxT+E5U6QqX78Td8h3z9kLVhmuNpA==
  template:
    metadata:
      creationTimestamp: null
      name: litellm-secrets
      namespace: litellm
    type: Opaque
