---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudnative-pg-cluster-litellm
  namespace: litellm
spec:
  encryptedData:
    password: AgCO+LKZfO9kkWfpIZKZRJu7YH3EkB3pQ7nXwWwVz1iUjoiFlKm8rimgqDbB59zeFcvnhHMlcX09VQCt0gX4Xyqc5nrERZO5EQb31A6Yk+VzmLpeK5ZUFKKK+iI5DW/MsWmDDXenIhnZNje7YRisM1tx+Ef0xFOig/pdIey+MOwYJeVFnVFj4RNj/NzuiMi3gOEx1u3ezh4pBgE/6zZilzw5qilOtRC/QWgAZIovA1TmoQd+HurXrVdoYPtRQoS2GoAKM6IiZliJL4lBbozZGUkIuH9lo5MCQztxLgXUQEa+8qPw0EuU9zg6K54sjiHDVW/ZqRYMGAlDMYWOR8bZNeJ1QApxSO2NU57Dqg3yZx1F/7F/UuDcIKiZW3muZaByy8twVu0XcQMWFzbxq6HavkBSrVVyfG2OeVWnCMj4oGj6P+tEswiRzpqntupu6LGbGILocjluGMqx1kc0ZHxrC+UEBdhFCA/5D4ANtAeqH4P0HlmG+4Mw2Sw/ZTUOzTVZCqq5xtgZj7Ghq4TkKLLHabs+bCzngl1I3slZOgzYmakDs32ApcbKIsxKhSJLV6IoNxe8oqdIq0SYBySYLlnaZDj6LsapqOt/wbMKspz75r82ACWOIoU8wWaV9ydF+RAn0edxuizBUQaSecKdPFjQQ52x9eG19/ieSPpE87nqzujvzahICN5VqpQ6NZqEkq8MTpyfATy+ZVlgBYTUlITZWYBWOW9SFNo1e788uEFtNJ+dbw==
    username: AgASKycmUbNFaqpg4d/EwhgRb6xTDim+vVb9ncYi2/rbcGo55YFYPVkvCq3nheJsFVdP44/+8drKhSxo0vZrvFg0+DDh8z9N0B7ybJ0oOoTCwq29OpM9J+e4l2/5IuzSGVtbmqThGGViq9/w9gqRa6pmmO4cMBLk2uRankkKagW4YNXgBuSy4smpSYSOqn3ilKUAFLeNp8mP2E6GzCR1EvXNavcrdBxBQHuaRFOK3TS2i5hGFlmOaWx7V1cFViaYn4nTGn2qgwXdgKWVUyCI8GVW7UdP64N/OpLkWR/K2Rob3U957Pc0YZP+HeWV4yjhBigp//P2bGfVFSM+/T7Z1aP+rP3H7GIoDVlCxRu84Xmni9KqJT8DoGRd+Ji8ejw0nOvpOobJ9jV3iEi4NvB4uJtmg7kseq2vsum/dXMC93djP/TfsCc2ttF5yitkqE9OhSLgI4Flh2MM91dQEQ8qpq6Acu/e9Td2N0McNOBMJd3OB4q2snV99xFp5KKVJ6zsdm6PmLiMuwTRRJKbdLaD6pi3gOADx8XuUPQGEeAI4VdckIfX2Njzd1NOPHj0Z4e+4Z8pbdnZ0j6Tr3zpIU5TUIj9EMdDvCiaO+Mhs72w2+wabtMXEmZsKYQLxWM7QwEDq5/5S5OOiDUZvLTCMI7YiWK5oK4fSO1ziEvHOVDoIeXExeyyb0/56P39j+q2wuY7jFn9nDKWNC+k
  template:
    metadata:
      creationTimestamp: null
      name: cloudnative-pg-cluster-litellm
      namespace: litellm
    type: Opaque
